# Generated by Django 4.2.7 on 2024-01-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesapayment',
            name='account_reference',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='transaction_description',
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mpesa.user'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
