# Generated by Django 4.2.7 on 2024-01-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0006_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=True, max_length=12, unique=True),
        ),
    ]
