# Generated by Django 4.2.7 on 2024-01-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0007_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
