# Generated by Django 4.2.7 on 2024-01-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0008_alter_wallet_amount_paid_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='username',
            field=models.CharField(default=True, max_length=12, unique=True),
        ),
    ]
